spring.application.name=timer-registration-api

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trs_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:trs_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

spring.flyway.enabled=true


app.jwt.secret=${APP_JWT_SECRET}

app.jwt.expiration-ms=86400000
