spring.application.name=timer-registration-api

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/trs_db
spring.datasource.username=trs_user
spring.datasource.password=trs_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

spring.flyway.enabled=true


app.jwt.secret=3d8b2066c8ee2cb2e32374d281674ec17b3a65cde696ab10ba27902c3c4ce6ac1503f55c45e0a24978dbcfb2a82de19289189d7972ae0359d26b19ea52816b8d

app.jwt.expiration-ms=86400000